services:
  order-db:
    image: postgres:18
    container_name: order-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"

  inventory-db:
    image: postgres:18
    container_name: inventory-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventorydb
    ports:
      - "5434:5432"

  payment-db:
    image: postgres:18
    container_name: payment-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: paymentdb
    ports:
      - "5435:5432"