server:
  port: 8082

spring:
  application:
    name: inventoryservice

  datasource:
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true