server:
  port: 8083

spring:
  application:
    name: paymentservice

  datasource:
    url: jdbc:postgresql://localhost:5435/paymentdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true